// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCttbyRNbr6KKpo3NxV0x-uunC0K0nmtZs',
    appId: '1:954722683748:android:23c1e7a8a0b4250dfac871',
    messagingSenderId: '954722683748',
    projectId: 'emandi-bb525',
    storageBucket: 'emandi-bb525.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkMHGpkvyThfj47fDN5qm8mudVnzDjGkY',
    appId: '1:954722683748:ios:7c348a4001568ae3fac871',
    messagingSenderId: '954722683748',
    projectId: 'emandi-bb525',
    storageBucket: 'emandi-bb525.appspot.com',
    androidClientId: '954722683748-jchkke58eij9h9b31lij16k6b55p4fvl.apps.googleusercontent.com',
    iosClientId: '954722683748-tl6uros1fmfiprlur5ktn68a7qsv32us.apps.googleusercontent.com',
    iosBundleId: 'com.example.eMandi',
  );

}